<?php
namespace models\rdb\mysql\query;

use models\rdb\query\Select as SelectCommon;

class Select extends SelectCommon
{
    public function selectAESDecrypt(string $column, string $key, string $alias): SelectCommon
    {
        // set value
        $this->setValues($this->getColumnName('aeskey'), $key);
        return SelectCommon::selectAESDecrypt($column, ':aeskey', $alias); // TODO: Change the autogenerated stub
    }
}