<?php
namespace models\rdb\oracle\query;

use models\rdb\query\Select as SelectCommon;

class Select extends SelectCommon
{
    /**
     * @param string $column
     * @return SelectCommon
     */
    public function selectDatetime(string $column): SelectCommon
    {
        return parent::selectDatetime('TO_CHAR('.$column.', \'YYYY-MM-DD HH24:MI:SS\') AS '.$column); // TODO: Change the autogenerated stub
    }
}